-- NAO INSERE SE DATA DE MATRICULA FOR DEPOIS DA DATA DE INÍCIO DA TURMA
CREATE TRIGGER COMPATIBILIDADE_MATRICULA
ON MATRICULA
AFTER INSERT, UPDATE

AS 

DECLARE @ID_MATRICULA INT

BEGIN		

SELECT @ID_MATRICULA = ID_MATRICULA 
FROM INSERTED 
	 
IF EXISTS(
	SELECT 
	  A.ID_ALUNO, 
	  A.DT_MATRICULA, 
	  M.ID_MATRICULA, 
	  T.DATA_INICIAL 

	FROM MATRICULA M
	  INNER JOIN ALUNO A
	ON A.ID_ALUNO = M.FK_ALUNO_ID_ALUNO
	  INNER JOIN TURMA T
	ON M.FK_TURMA_ID_TURMA = T.ID_TURMA
	WHERE T.DATA_INICIAL < A.DT_MATRICULA
	)
DELETE FROM MATRICULA
WHERE ID_MATRICULA = @ID_MATRICULA

END

-- TESTANDO

-- NAO PASSA
INSERT INTO MATRICULA
VALUES
(74, 15)

-- PASSA NO TESTE
INSERT INTO MATRICULA
VALUES
(75, 5)

select * from MATRICULA
where ID_MATRICULA = 143


-- ADICIONANDO DIAS SE AULAS FOREM CADASTRADAS NO FDS
CREATE TRIGGER ADD_DIAS
ON PRESENCA
AFTER INSERT, UPDATE

AS

DECLARE @DATA_AULA DATE
DECLARE @DIA_AULA DATE

BEGIN 

SELECT @DATA_AULA = DATA_AULA FROM INSERTED
SELECT @DIA_AULA = @DATA_AULA

IF DATENAME(WEEKDAY, @DATA_AULA) = 'SÁBADO' OR  DATENAME(WEEKDAY, @DATA_AULA) = 'DOMINGO'

UPDATE PRESENCA
SET DATA_AULA = DATEADD(DAY, 2, @DATA_AULA)
WHERE DATA_AULA = @DIA_AULA

END

-- TESTANDO

INSERT INTO PRESENCA
VALUES ('2022-02-05', 1, 44)
INSERT INTO PRESENCA
VALUES ('2022-02-06', 1, 45)

SELECT * FROM PRESENCA
where ID_PRESENCA > 25
